@startuml
' TODO: draw network segmentation diagram here
title Network Segmentation - Gray Logic Stack

' Example stencil:
rectangle "Control LAN" { }
rectangle "CCTV LAN" { }
rectangle "Guest LAN" { }
"Gray Logic Node" --> "VPS / Remote"

@enduml
