/**
 * Retro theme — LVGL v9 theme with 1960s/70s instrument panel aesthetic.
 *
 * Uses custom generated fonts (Nixie One for digits, Share Tech Mono for text)
 * and aggressive shadow/glow styling to simulate vintage hardware.
 */
#include "theme/retro_theme.h"
#include "theme/retro_colors.h"

/* ── Extern font declarations (generated by lv_font_conv) ────────── */
extern const lv_font_t nixie_font;      /* 48px — big numeric displays */
extern const lv_font_t nixie_font_sm;   /* 28px — smaller numeric displays */
extern const lv_font_t mono_font;       /* 16px — body text */
extern const lv_font_t mono_font_lg;    /* 20px — section headers */

/* ── Static style objects ─────────────────────────────────────────── */

static lv_style_t style_screen;
static lv_style_t style_btn;
static lv_style_t style_btn_pressed;
static lv_style_t style_arc;
static lv_style_t style_arc_indicator;
static lv_style_t style_arc_knob;
static lv_style_t style_label;
static lv_style_t style_slider;
static lv_style_t style_slider_indicator;
static lv_style_t style_slider_knob;

static bool styles_initialised = false;

/* ── Style initialisation ─────────────────────────────────────────── */

static void init_styles(void)
{
    if (styles_initialised) return;
    styles_initialised = true;

    /* Screen background — very dark with mono font default */
    lv_style_init(&style_screen);
    lv_style_set_bg_color(&style_screen, RETRO_NEAR_BLACK);
    lv_style_set_bg_opa(&style_screen, LV_OPA_COVER);
    lv_style_set_text_color(&style_screen, RETRO_AMBER);
    lv_style_set_text_font(&style_screen, &mono_font);

    /* Bakelite button — heavy 3D brown with strong shadow */
    lv_style_init(&style_btn);
    lv_style_set_bg_color(&style_btn, RETRO_DARK_BROWN);
    lv_style_set_bg_grad_color(&style_btn, RETRO_NEAR_BLACK);
    lv_style_set_bg_grad_dir(&style_btn, LV_GRAD_DIR_VER);
    lv_style_set_bg_opa(&style_btn, LV_OPA_COVER);
    lv_style_set_border_color(&style_btn, RETRO_MED_BROWN);
    lv_style_set_border_width(&style_btn, 2);
    lv_style_set_radius(&style_btn, 6);
    lv_style_set_shadow_color(&style_btn, lv_color_black());
    lv_style_set_shadow_width(&style_btn, 12);
    lv_style_set_shadow_offset_y(&style_btn, 4);
    lv_style_set_shadow_opa(&style_btn, LV_OPA_70);
    lv_style_set_text_color(&style_btn, RETRO_AMBER);
    lv_style_set_text_font(&style_btn, &mono_font);
    lv_style_set_pad_hor(&style_btn, 10);
    lv_style_set_pad_ver(&style_btn, 6);

    /* Button pressed — slam down: shadow vanishes, bg darkens */
    lv_style_init(&style_btn_pressed);
    lv_style_set_bg_color(&style_btn_pressed, RETRO_NEAR_BLACK);
    lv_style_set_bg_grad_color(&style_btn_pressed, RETRO_DARK_BROWN);
    lv_style_set_shadow_width(&style_btn_pressed, 2);
    lv_style_set_shadow_offset_y(&style_btn_pressed, 1);
    lv_style_set_translate_y(&style_btn_pressed, 3);
    lv_style_set_border_color(&style_btn_pressed, RETRO_AMBER_DIM);

    /* Arc — wider track, darker background for contrast */
    lv_style_init(&style_arc);
    lv_style_set_arc_color(&style_arc, lv_color_hex(0x1A1F22));
    lv_style_set_arc_width(&style_arc, 14);
    lv_style_set_arc_rounded(&style_arc, true);

    /* Arc indicator — bright amber with glow */
    lv_style_init(&style_arc_indicator);
    lv_style_set_arc_color(&style_arc_indicator, RETRO_AMBER);
    lv_style_set_arc_width(&style_arc_indicator, 14);
    lv_style_set_arc_rounded(&style_arc_indicator, true);

    /* Arc knob — brown tactile knob */
    lv_style_init(&style_arc_knob);
    lv_style_set_bg_color(&style_arc_knob, RETRO_MED_BROWN);
    lv_style_set_bg_opa(&style_arc_knob, LV_OPA_COVER);
    lv_style_set_pad_all(&style_arc_knob, 5);
    lv_style_set_border_color(&style_arc_knob, RETRO_AMBER);
    lv_style_set_border_width(&style_arc_knob, 1);
    lv_style_set_shadow_color(&style_arc_knob, RETRO_GLOW_SHADOW);
    lv_style_set_shadow_width(&style_arc_knob, 6);
    lv_style_set_shadow_opa(&style_arc_knob, LV_OPA_40);

    /* Labels — mono font, amber */
    lv_style_init(&style_label);
    lv_style_set_text_color(&style_label, RETRO_AMBER);
    lv_style_set_text_font(&style_label, &mono_font);

    /* Slider track — dark groove */
    lv_style_init(&style_slider);
    lv_style_set_bg_color(&style_slider, lv_color_hex(0x1A1F22));
    lv_style_set_bg_opa(&style_slider, LV_OPA_COVER);
    lv_style_set_radius(&style_slider, 4);
    lv_style_set_border_color(&style_slider, RETRO_CHARCOAL);
    lv_style_set_border_width(&style_slider, 1);

    /* Slider indicator — amber fill */
    lv_style_init(&style_slider_indicator);
    lv_style_set_bg_color(&style_slider_indicator, RETRO_AMBER);
    lv_style_set_bg_grad_color(&style_slider_indicator, RETRO_BURNT_ORANGE);
    lv_style_set_bg_grad_dir(&style_slider_indicator, LV_GRAD_DIR_HOR);
    lv_style_set_bg_opa(&style_slider_indicator, LV_OPA_COVER);
    lv_style_set_radius(&style_slider_indicator, 4);

    /* Slider knob — heavy brown knob with shadow */
    lv_style_init(&style_slider_knob);
    lv_style_set_bg_color(&style_slider_knob, RETRO_DARK_BROWN);
    lv_style_set_bg_grad_color(&style_slider_knob, RETRO_MED_BROWN);
    lv_style_set_bg_grad_dir(&style_slider_knob, LV_GRAD_DIR_VER);
    lv_style_set_bg_opa(&style_slider_knob, LV_OPA_COVER);
    lv_style_set_radius(&style_slider_knob, 4);
    lv_style_set_pad_all(&style_slider_knob, 7);
    lv_style_set_border_color(&style_slider_knob, RETRO_AMBER_DIM);
    lv_style_set_border_width(&style_slider_knob, 1);
    lv_style_set_shadow_color(&style_slider_knob, lv_color_black());
    lv_style_set_shadow_width(&style_slider_knob, 8);
    lv_style_set_shadow_offset_y(&style_slider_knob, 3);
    lv_style_set_shadow_opa(&style_slider_knob, LV_OPA_60);
}

/* ── Theme apply callback ─────────────────────────────────────────── */

static void theme_apply_cb(lv_theme_t *th, lv_obj_t *obj)
{
    (void)th;

    if (lv_obj_check_type(obj, &lv_obj_class)) {
        lv_obj_t *parent = lv_obj_get_parent(obj);
        if (parent == NULL) {
            lv_obj_add_style(obj, &style_screen, 0);
        }
    }
    else if (lv_obj_check_type(obj, &lv_button_class)) {
        lv_obj_add_style(obj, &style_btn, 0);
        lv_obj_add_style(obj, &style_btn_pressed, LV_STATE_PRESSED);
    }
    else if (lv_obj_check_type(obj, &lv_arc_class)) {
        lv_obj_add_style(obj, &style_arc, LV_PART_MAIN);
        lv_obj_add_style(obj, &style_arc_indicator, LV_PART_INDICATOR);
        lv_obj_add_style(obj, &style_arc_knob, LV_PART_KNOB);
    }
    else if (lv_obj_check_type(obj, &lv_label_class)) {
        lv_obj_add_style(obj, &style_label, 0);
    }
    else if (lv_obj_check_type(obj, &lv_slider_class)) {
        lv_obj_add_style(obj, &style_slider, LV_PART_MAIN);
        lv_obj_add_style(obj, &style_slider_indicator, LV_PART_INDICATOR);
        lv_obj_add_style(obj, &style_slider_knob, LV_PART_KNOB);
    }
}

/* ── Public API ───────────────────────────────────────────────────── */

void retro_theme_init(lv_display_t *disp)
{
    init_styles();

    lv_theme_t *th = lv_theme_default_init(
        disp,
        RETRO_AMBER,
        RETRO_BURNT_ORANGE,
        true,
        &mono_font
    );

    lv_theme_set_apply_cb(th, theme_apply_cb);
    lv_display_set_theme(disp, th);
}

const lv_font_t *retro_font_heading(void)
{
    return &mono_font_lg;
}

const lv_font_t *retro_font_body(void)
{
    return &mono_font;
}

const lv_font_t *retro_font_nixie(void)
{
    return &nixie_font;
}

const lv_font_t *retro_font_nixie_sm(void)
{
    return &nixie_font_sm;
}
